// Re-export from snapshots-db so index.ts has one import location
export {
  listDesigns,
  getDesign,
  createDesign,
  clearDesignWorkspace,
  renameDesign,
  setDesignThumbnail,
  softDeleteDesign,
  duplicateDesign,
  deleteDesignFilesByPrefix,
  listDesignFiles,
  listSnapshots,
  getSnapshot,
  createSnapshot,
  deleteSnapshot,
  upsertDesignFile,
  updateDesignProjectInstructions,
  updateDesignWorkspace,
  viewDesignFile,
  listChatMessages,
  appendChatMessage,
  updateChatToolCallStatus,
  seedChatFromSnapshots,
  createComment,
  listComments,
  listPendingEdits,
  updateComment,
  deleteComment,
  markCommentsApplied,
  normalizeDesignFilePath,
  listFolders,
  createFolder,
  renameFolder,
  deleteFolder,
  moveDesignToFolder,
} from './snapshots-db.js';
