/**
 * Pure markdown composer for the diagnostic `summary.md` file. The same
 * output is used both inside the zipped bug-report bundle and as the
 * GitHub issue body, so this module must stay free of I/O and of any
 * process-level state (no Date.now, no app.getPath, etc.).
 */

import type { ActionTimelineEntry, DiagnosticEventRow } from '@open-codesign/shared';
import { normalizeFrame } from '@open-codesign/shared/fingerprint';

export interface SummaryInput {
  event: DiagnosticEventRow;
  appVersion: string;
  platform: string;
  electronVersion: string;
  nodeVersion: string;
  timeline: ActionTimelineEntry[];
  recentLogTail: string[];
  notes: string;
  includePromptText: boolean;
  includePaths: boolean;
  includeUrls: boolean;
  includeTimeline: boolean;
}

const MAX_BYTES = 20 * 1024;
const TRUNCATION_SUFFIX = '\n\n_(summary truncated to 20 KB — full bundle attached as zip)_';
const PROMPT_OMITTED = '<prompt omitted>';
const PATH_OMITTED = '<path omitted>';
const URL_OMITTED = '<url omitted>';
const PATH_REGEX =
  /(?:(?:[A-Za-z]:\\|\\\\)[^\s'"<>`]+|(?:[/\\](?:Users|home|root|opt|Applications|var|tmp|etc|private))[/\\][^\s'"<>`]+|~[/\\][^\s'"<>`]+)/g;
const URL_REGEX = /(?:https?|wss?|file):\/\/[^\s'"<>]+/g;

export function composeSummaryMarkdown(input: SummaryInput): string {
  const { event } = input;
  const occurredAt = new Date(event.ts).toISOString();
  const runId = event.runId ?? '(none)';
  const transient = event.transient ? 'yes' : 'no';

  const message = redact(event.message, input);
  const stackSection = renderStack(event.stack);
  const upstreamSection = renderUpstream(event, input);
  const timelineSection = renderTimeline(input);
  const logSection = renderLogTail(input);
  const notesSection = renderNotes(input.notes);

  const lines: string[] = [];
  lines.push(`# Diagnostic Report — ${event.code}`);
  lines.push('');
  lines.push(`**Fingerprint:** \`${event.fingerprint}\`  (seen ${event.count} times)`);
  lines.push(`**Occurred at:** ${occurredAt}`);
  lines.push(`**Run id:** \`${runId}\``);
  lines.push(`**Scope:** \`${event.scope}\``);
  lines.push('');
  lines.push('## Environment');
  lines.push(`- App: ${input.appVersion}`);
  lines.push(`- Platform: ${input.platform}`);
  lines.push(`- Electron: ${input.electronVersion} / Node: ${input.nodeVersion}`);
  lines.push('');
  lines.push('## Error');
  lines.push(`- Code: \`${event.code}\``);
  lines.push(`- Message: ${message}`);
  lines.push(`- Level: ${event.level}`);
  lines.push(`- Transient (retried and succeeded): ${transient}`);
  lines.push('');
  lines.push('### Stack (top 5 frames)');
  lines.push(stackSection);

  if (upstreamSection !== undefined) {
    lines.push('');
    lines.push('### Upstream context');
    lines.push(upstreamSection);
  }

  lines.push('');
  lines.push('## User actions (last 60 s)');
  lines.push(timelineSection);
  lines.push('');
  lines.push('## Recent log tail');
  lines.push(logSection);
  lines.push('');
  lines.push('## Reporter notes');
  lines.push(notesSection);
  lines.push('');
  lines.push('---');
  lines.push(`Generated by open-codesign ${input.appVersion}.`);

  const body = lines.join('\n');
  return capLength(body);
}

function renderStack(stack: string | undefined): string {
  if (typeof stack !== 'string' || stack.trim().length === 0) {
    return '```\n(no stack)\n```';
  }
  const frames: string[] = [];
  for (const raw of stack.split('\n')) {
    const trimmed = raw.trim();
    if (!trimmed.startsWith('at ')) continue;
    frames.push(normalizeFrame(trimmed));
    if (frames.length >= 5) break;
  }
  if (frames.length === 0) return '```\n(no stack)\n```';
  return ['```', ...frames, '```'].join('\n');
}

function renderUpstream(event: DiagnosticEventRow, input: SummaryInput): string | undefined {
  if (event.scope !== 'provider') return undefined;
  const ctx = event.context;
  if (ctx === undefined) return undefined;
  const provider = asString(ctx['upstream_provider']);
  const status = asString(ctx['upstream_status']);
  const requestId = asString(ctx['upstream_request_id']);
  const retryCount = asString(ctx['retry_count']);
  const bodyHead = asString(ctx['redacted_body_head']);
  const scrubbedBody =
    bodyHead === undefined
      ? undefined
      : input.includePromptText
        ? bodyHead
        : scrubPromptInLine(bodyHead);
  const redactedBody =
    scrubbedBody === undefined
      ? undefined
      : truncate(
          redactPathsAndUrls(scrubbedBody, {
            includePaths: input.includePaths,
            includeUrls: input.includeUrls,
          }),
          400,
        );
  const rows: string[] = [];
  if (provider !== undefined) rows.push(`- Provider: ${provider}`);
  if (status !== undefined) rows.push(`- Status: ${status}`);
  if (requestId !== undefined) rows.push(`- Request-Id: ${requestId}`);
  if (retryCount !== undefined) rows.push(`- Retry count: ${retryCount}`);
  if (redactedBody !== undefined) rows.push(`- Body head: ${redactedBody}`);
  if (rows.length === 0) return undefined;
  return rows.join('\n');
}

function renderTimeline(input: SummaryInput): string {
  if (!input.includeTimeline) {
    return '_(timeline omitted — user chose not to include)_';
  }
  if (input.timeline.length === 0) return '_(no recent actions)_';
  const sorted = [...input.timeline].sort((a, b) => b.ts - a.ts);
  const rows: string[] = [];
  rows.push('| Offset | Type | Details |');
  rows.push('|---|---|---|');
  for (const entry of sorted) {
    const offset = Math.round((entry.ts - input.event.ts) / 1000);
    const offsetLabel = `${offset} s`;
    const details = formatTimelineData(entry.data);
    rows.push(`| ${offsetLabel} | ${entry.type} | ${details} |`);
  }
  return rows.join('\n');
}

function formatTimelineData(data: Record<string, unknown> | undefined): string {
  if (data === undefined) return '—';
  const parts: string[] = [];
  for (const [key, value] of Object.entries(data)) {
    parts.push(`${key}=${formatValue(value)}`);
  }
  return parts.length === 0 ? '—' : parts.join(', ');
}

function formatValue(value: unknown): string {
  if (typeof value === 'boolean') return value ? 'yes' : 'no';
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'number' || typeof value === 'string') return String(value);
  return JSON.stringify(value);
}

function renderLogTail(input: SummaryInput): string {
  const lines = input.recentLogTail.map((line) => {
    const scrubbed = input.includePromptText ? line : scrubPromptInLine(line);
    return redactPathsAndUrls(scrubbed, {
      includePaths: input.includePaths,
      includeUrls: input.includeUrls,
    });
  });
  if (lines.length === 0) return '```\n(no log tail)\n```';
  return ['```', ...lines, '```'].join('\n');
}

export function scrubPromptInLine(line: string): string {
  return line
    .replace(/("prompt"\s*:\s*)"(?:[^"\\]|\\.)*"/g, '$1"<prompt omitted>"')
    .replace(/(\bprompt\s*[:=]\s*)"(?:[^"\\]|\\.)*"/g, '$1"<prompt omitted>"')
    .replace(/(\bprompt\s*[:=]\s*)`(?:[^`\\]|\\.)*`/g, '$1`<prompt omitted>`');
}

function renderNotes(notes: string): string {
  return notes.trim().length === 0 ? '(none)' : notes.trim();
}

function redact(text: string, input: SummaryInput): string {
  let out = text;
  if (!input.includePromptText && looksLikePrompt(out)) {
    out = PROMPT_OMITTED;
  }
  return redactPathsAndUrls(out, {
    includePaths: input.includePaths,
    includeUrls: input.includeUrls,
  });
}

export function redactPathsAndUrls(
  text: string,
  opts: { includePaths: boolean; includeUrls: boolean },
): string {
  let out = text;
  if (!opts.includePaths) out = out.replace(PATH_REGEX, PATH_OMITTED);
  if (!opts.includeUrls) out = out.replace(URL_REGEX, URL_OMITTED);
  return out;
}

function looksLikePrompt(text: string): boolean {
  // JSON key / field markers that unambiguously indicate prompt bodies.
  // These are structural — they only appear when code explicitly put a
  // prompt behind a named field, not in natural-language messages.
  if (/"prompt"\s*:\s*"/.test(text)) return true;
  if (/\bprompt\s*[:=]\s*"/.test(text)) return true;
  if (/\bprompt\s*[:=]\s*`/.test(text)) return true;
  // Intentionally no heuristic on length + punctuation: Chinese error
  // messages frequently contain 请/请问/请检查 and aren't prompts.
  return false;
}

function truncate(text: string, max: number): string {
  if (text.length <= max) return text;
  return `${text.slice(0, max)}…`;
}

function asString(value: unknown): string | undefined {
  if (value === undefined || value === null) return undefined;
  if (typeof value === 'string') return value;
  if (typeof value === 'number' || typeof value === 'boolean') {
    return String(value);
  }
  return JSON.stringify(value);
}

function capLength(body: string): string {
  const encoder = new TextEncoder();
  if (encoder.encode(body).byteLength <= MAX_BYTES) return body;
  const budget = MAX_BYTES - encoder.encode(TRUNCATION_SUFFIX).byteLength;
  let lo = 0;
  let hi = body.length;
  while (lo < hi) {
    const mid = (lo + hi + 1) >>> 1;
    if (encoder.encode(body.slice(0, mid)).byteLength <= budget) lo = mid;
    else hi = mid - 1;
  }
  return `${body.slice(0, lo)}${TRUNCATION_SUFFIX}`;
}
